DROP TABLE OrdersTable_TASK2;
CREATE TABLE OrdersTable_TASK2(
ORDER_ID TEXT,
ORDER_DATE DATE,
CUSTOMER_ID TEXT,
PRODUCT_NAME TEXT,
SALES NUMERIC(10,2),
QUANTITY INT,
PROFIT NUMERIC(10,2),
DISCOUNT NUMERIC(10,2)
);

COPY OrdersTable_TASK2(ORDER_ID, ORDER_DATE, CUSTOMER_ID, PRODUCT_NAME, SALES, QUANTITY, PROFIT, DISCOUNT)
FROM 'C:\Maincraft Internship (April 14 to May)\Task 2 Abhradeep\OrdersTable_Task2_Abhradeep.csv' 
DELIMITER ',' 
CSV HEADER 
QUOTE '"' 
ESCAPE '"';

SELECT * FROM OrdersTable_TASK2;

DROP TABLE CustomersTable_TASK2;
CREATE TABLE CustomersTable_TASK2(
CUSTOMER_ID TEXT,
CUSTOMER_NAME VARCHAR(100),
Region VARCHAR(50),
CITY VARCHAR(50),
STATE VARCHAR(50)
);

COPY CustomersTable_TASK2(CUSTOMER_ID, CUSTOMER_NAME,region , CITY, STATE)
FROM 'C:\Maincraft Internship (April 14 to May)\Task 2 Abhradeep\CustomersTable_Task2_Abhradeep.csv'
DELIMITER ','
CSV HEADER
QUOTE '"'
ESCAPE '"';

SELECT * FROM CustomersTable_TASK2;


--INNER JOIN
SELECT O.ORDER_ID, O.ORDER_DATE, O.CUSTOMER_ID, O.PRODUCT_NAME, O.SALES, O.QUANTITY, O.PROFIT,O.DISCOUNT,
       C.CUSTOMER_ID, C.CUSTOMER_NAME,C.REGION , C.CITY, C.STATE 
FROM OrdersTable_TASK2 O
INNER JOIN
CustomersTable_TASK2 C
ON O.CUSTOMER_ID= C.CUSTOMER_ID;

--TOTAL SALES BY REGION
SELECT C.REGION, SUM(O.SALES) AS TOTAL_SALES
FROM Customerstable_TASK2 C 
JOIN OrdersTable_TASK2 O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.REGION
ORDER BY TOTAL_SALES DESC;

--PROFIT MARGIN BY CATEGORY
SELECT product_name, SUM(PROFIT)/SUM(SALES) AS PROFIT_MARGIN
FROM OrdersTable_TASK2
GROUP BY product_name
ORDER BY PROFIT_MARGIN DESC;

--MONTHLY SALES TREND
SELECT
EXTRACT (MONTH FROM ORDER_DATE) AS MONTHS,
SUM(SALES) AS MONTHLY_SALES
FROM OrdersTable_TASK2
GROUP BY MONTHS
ORDER BY MONTHS;

--TOP 5 CUSTOMERS BY REVENUE
SELECT C.CUSTOMER_NAME, SUM(O.SALES) AS TOTAL_REVENUE
FROM CustomersTable_TASK2 C
JOIN OrdersTable_TASK2 O
ON C.CUSTOMER_ID=  O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;